config/routes.rb
Rails.application.routes.draw do
  root to: 'urls#index'
  resources :urls, only: [:create, :show]

  # shortened url
  get '/:code', to: 'urls#get', as: 'get_url'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates_format_of :original_url, with: /\A#{URI::regexp}\z/, message: 'is invalid.'
  validates_format_of :shortened_url, with: /\A(?!url)[a-zA-Z0-9_-]*\z/i, 
    message: 'can only consist of alphabets/numbers/underscores/hiphens, and cannot begin with \'url\'.'

  default_scope -> { order(updated_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  # homepage
  def index
    @url = Url.new
    @urls = Url.all
  end

  def create
    @url = Url.new(url_params)
    @url.shortened_url = random_code if @url.shortened_url.blank?
    @url.save!
    redirect_to root_path, notice: "Short url successfully created! Here: #{request.base_url}/#{@url.shortened_url}"
  rescue StandardError => e
    flash[:error] = "Oops! #{e}"
    redirect_to root_path
  end

  # Shortened url requests come here
  def get
    url = Url.find_by!(shortened_url: params[:code])
    url.count += 1
    url.save!
    redirect_to url.original_url
  rescue StandardError
    flash[:error] = "That's not right. Did you mistype the url?"
    redirect_to root_path
  end

  # detailed page of the shortened url
  def show
    url = Url.find(params[:id].to_i)
    @stats = {
      shortened_url: "#{request.base_url}/#{url.shortened_url}",
      original_url: url.original_url,
      usage_count: url.count,
      created_at: url.created_at,
      most_recent_use: url.updated_at
    }
  end

  private
    def url_params
      params.require(:url).permit(:original_url, :shortened_url)
    end

    # generate random 4-charcter-long string
    def random_code
      existing_codes = Url.select(:shortened_url).map(&:shortened_url)
      new_code = [*('A'..'Z'),*('0'..'9')].shuffle[0,4].join

      while existing_codes.include?(new_code)
        new_code = [*('A'..'Z'), *('0'..'9')].shuffle[0,4].join
      end

      new_code
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html 
  head
    title URL shortener
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    / script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"
    / script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"


  body
    .container-fluid
      .row
        .jumbotron.col-md-12
          h1.text-center URL SHORTENER
      .row
        .col-md-12.text-center
          = flash[:notice] || flash[:error]
      = yield

app/views/urls/_new_url.html.slim
= form_with model: @url, url: urls_path do |f|
  .form-group
    .col-md-10.mb-1
      = f.label :original_url, 'the url you want to shorten' 
      = f.text_field :original_url, class: 'form-control form-inline'
    .col-md-10.mb-1
      = f.label :shortened_url, '(optional) custom shortened url. Please provide a valid format' 
      = f.text_field :shortened_url, class: 'form-control form-inline'
    .col-md-2
      = f.submit 'LOSE WEIGHT!', class: 'btn btn-warning text-white'

app/views/urls/index.html.slim
.row.mb-3
  .col-md-6.mx-auto
    .card
      .card-header.text-white.bg-warning
        h5 CREATE NEW 
      .card-body
        = render 'new_url'

.row
  .col-md-6.mx-auto
    .card
      .card-header.text-white.bg-info
        h5 HISTORY & STATS
      .card-body
        table.table
          thead
            tr
              th short url
              th original url
              th most recent visit 
              th detail
          tbody
            - @urls.each do |url|
              tr 
                td #{request.base_url}/#{url.shortened_url}
                td = link_to url.original_url
                td = url.updated_at.strftime('%F %H:%M')
                td = link_to 'STATS', url_path(url.id), class: 'btn btn-info'

app/views/urls/show.html.slim
.row
  .col-md-6.mx-auto
    .card
      .card-header.text-white.bg-info
        h5 DETAILS
      .card-body
        table.table
          tbody
            - @stats.each do |key, value|
              tr 
                td = key.to_s.humanize
                td = value